//
// Generated file, do not edit! Created by opp_msgtool 6.3 from transportlayer/tcp/TcpOpenSubflowCommand.msg.
//

#ifndef __INET_TCPOPENSUBFLOWCOMMAND_M_H
#define __INET_TCPOPENSUBFLOWCOMMAND_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class TcpOpenSubflowCommand;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/transportlayer/contract/tcp/TcpCommand_m.h" // import inet.transportlayer.contract.tcp.TcpCommand


namespace inet {

/**
 * Class generated from <tt>transportlayer/tcp/TcpOpenSubflowCommand.msg:13</tt> by opp_msgtool.
 * <pre>
 * class TcpOpenSubflowCommand extends TcpCommand
 * {
 *     L3Address localAddr;
 *     L3Address remoteAddr;
 *     int localPort;
 *     int remotePort;
 *     int newSocketId;
 * }
 * </pre>
 */
class TcpOpenSubflowCommand : public ::inet::TcpCommand
{
  protected:
    L3Address localAddr;
    L3Address remoteAddr;
    int localPort = 0;
    int remotePort = 0;
    int newSocketId = 0;

  private:
    void copy(const TcpOpenSubflowCommand& other);

  protected:
    bool operator==(const TcpOpenSubflowCommand&) = delete;

  public:
    TcpOpenSubflowCommand();
    TcpOpenSubflowCommand(const TcpOpenSubflowCommand& other);
    virtual ~TcpOpenSubflowCommand();
    TcpOpenSubflowCommand& operator=(const TcpOpenSubflowCommand& other);
    virtual TcpOpenSubflowCommand *dup() const override {return new TcpOpenSubflowCommand(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const L3Address& getLocalAddr() const;
    virtual L3Address& getLocalAddrForUpdate() { return const_cast<L3Address&>(const_cast<TcpOpenSubflowCommand*>(this)->getLocalAddr());}
    virtual void setLocalAddr(const L3Address& localAddr);

    virtual const L3Address& getRemoteAddr() const;
    virtual L3Address& getRemoteAddrForUpdate() { return const_cast<L3Address&>(const_cast<TcpOpenSubflowCommand*>(this)->getRemoteAddr());}
    virtual void setRemoteAddr(const L3Address& remoteAddr);

    virtual int getLocalPort() const;
    virtual void setLocalPort(int localPort);

    virtual int getRemotePort() const;
    virtual void setRemotePort(int remotePort);

    virtual int getNewSocketId() const;
    virtual void setNewSocketId(int newSocketId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TcpOpenSubflowCommand& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TcpOpenSubflowCommand& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::TcpOpenSubflowCommand *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::TcpOpenSubflowCommand*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_TCPOPENSUBFLOWCOMMAND_M_H

