//
// Generated file, do not edit! Created by opp_msgtool 6.1 from common/DataSequenceNumberTag.msg.
//

#ifndef __INET_DATASEQUENCENUMBERTAG_M_H
#define __INET_DATASEQUENCENUMBERTAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class DataSequenceNumberTag;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/TagBase_m.h" // import inet.common.TagBase

#include "inet/common/Units_m.h" // import inet.common.Units


namespace inet {

/**
 * Class generated from <tt>common/DataSequenceNumberTag.msg:9</tt> by opp_msgtool.
 * <pre>
 * class DataSequenceNumberTag extends TagBase
 * {
 *     unsigned int dataSequenceNumber;
 * }
 * </pre>
 */
class DataSequenceNumberTag : public ::inet::TagBase
{
  protected:
    unsigned int dataSequenceNumber = 0;

  private:
    void copy(const DataSequenceNumberTag& other);

  protected:
    bool operator==(const DataSequenceNumberTag&) = delete;

  public:
    DataSequenceNumberTag();
    DataSequenceNumberTag(const DataSequenceNumberTag& other);
    virtual ~DataSequenceNumberTag();
    DataSequenceNumberTag& operator=(const DataSequenceNumberTag& other);
    virtual DataSequenceNumberTag *dup() const override {return new DataSequenceNumberTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned int getDataSequenceNumber() const;
    virtual void setDataSequenceNumber(unsigned int dataSequenceNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DataSequenceNumberTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DataSequenceNumberTag& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::DataSequenceNumberTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::DataSequenceNumberTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_DATASEQUENCENUMBERTAG_M_H

